### ISSUE TITLE
Server implementation

### ISSUE THREAD

**Issue by heri16** [kbrw/mailibex#1]
This project is nice, would like to contribute. It would be nice if you could publish a barebones smtp server and client implementation to get us started.

**Comment by awetzel** [comment]
Hello heri16, thank you for your interest, sorry for the late answer I do not understand why but I did not saw the github notification. unfortunatly I have to much work for now to start a barebone implementation, I think I will have some time in 2 months. The simpler is the client, you could use https://github.com/Vagabond/gen_smtp gen_smtp_client.erl as a starting point. For the server, the implementation of gen_smtp_server_session could be "easily" integrated into a ranch protocol, but the hard part is to define a good high level interface above server implementation. Gen_smtp handlers are a good one, but too low level to easily use SMTP as a message broker for instance.
