### ISSUE TITLE
Doesn't compile under 1.5.2

### ISSUE THREAD

**Issue by cdegroot** [kbrw/mailibex#18]
Apart from a bunch of compiler warnings about deprecated stuff, 

```elixir
== Compilation error in file lib/dmarc.ex ==
** (CompileError) Elixir.DMARC: function organization/1+79850:
  Internal consistency check failed - please report this bug.
  Instruction: {test,bs_test_tail2,{f,8268},[{x,14},0]}
  Error:       {no_bsm_context,{x,14}}:

    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

I haven't been able to find out when/why this happens exactly yet, logging an issue so we can coordinate work if more people are looking at this.

**Comment by antoinereyt** [comment]
Hy,

Can you give more details about your env. ?

I had tested many versions erlang/elixir thanks to Travis, but I still cannot reproduce.

**Comment by cdegroot** [comment]
I think it was on my work MacOS/Sierra laptop. The issue is that I since then moved that laptop to Linux, so reproducing it on that exact environment will be hard. If Travis is happy, let's blame me for not properly filing a bug report and close this :-)
