### ISSUE TITLE
Error during compulation

### ISSUE THREAD

**Issue by Qqwy** [kbrw/mailibex#21]
It does not seem to compile currently.

Steps:

1. Create a new mix project.
2. Add `{:mailibex, "~> 0.1.4"},` to the deps.
3. Run `mix deps.get`
3. Run `mix compile` or `iex -S mix`, which crashes:

```
** (CompileError) Elixir.DMARC: function organization/1+81247:
  Internal consistency check failed - please report this bug.
  Instruction: {test,bs_test_tail2,{f,8408},[{x,14},0]}
  Error:       {no_bsm_context,{x,14}}:

    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

```

**Comment by Shakadak** [comment]
Hi,

I'm closing this since I can't reproduce it with `0.1.5`.

Still thank you for your time, and sorry for the late reply.

**Comment by Qqwy** [comment]
Heh, no worries. Life goes on.

Better late than never :wink: .
