### ISSUE TITLE
Body parsing with  charset="utf-8" and Content-Transfer-Encoding: 8bit not working

### ISSUE THREAD

**Issue by theMarinac** [kbrw/mailibex#25]
I have 
```eml
Content-Type: text/plain;
	charset="utf-8"
Content-Transfer-Encoding: 8bit
```
and
```eml
Content-Type: text/html;
	charset="utf-8"
Content-Transfer-Encoding: 8bit
```
And body content is not parsed when I am using 
```elixir
raw_imap_response
|> MimeMail.from_string
|> MimeMail.decode_body
```

Email is from gramarly it will be attached in file. Can someone please take a look?
Thanks
[gramarly.zip](https://github.com/kbrw/mailibex/files/3662641/gramarly.zip)

**Comment by jschoch** [comment]
looks like this is fixed here: https://github.com/kbrw/mailibex/pull/24

Wondering if the pull will be accepted soon?
