### ISSUE TITLE
New version on Hex.

### ISSUE THREAD

**Issue by Argonus** [kbrw/mailibex#28]
@GuillaumeMilan 
Hi, I saw that recently You've updated the package to resolve compile-time warnings, could you release a new version to hex? Or there is something needed to do that. If yes, can I help you some way?

**Comment by GuillaumeMilan** [comment]
Hello @Argonus.
We will do it as soon as possible.

**Comment by GuillaumeMilan** [comment]
Hello @Argonus 
The package is now published under the version 0.1.6
